name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: [bug]
assignees: 
  - Andre-Diamond

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this bug report."

  - type: input
    id: title
    attributes:
      label: Bug Title
      description: "Provide a brief, descriptive title for the bug."
      placeholder: "Enter title here"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A detailed description of the issue."
      placeholder: "Describe the bug in detail..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: "Select the severity level of the bug."
      options:
        - label: "Critical"
        - label: "High"
        - label: "Medium"
        - label: "Low"
    validations:
      required: true

  - type: radiobuttons
    id: frequency
    attributes:
      label: Frequency of occurrence
      description: "How often does the bug occur?"
      options:
        - label: "Always"
        - label: "Sometimes"
        - label: "Rarely"
    validations:
      required: true

  - type: checkboxes
    id: reproduce
    attributes:
      label: Can you reproduce the bug?
      description: "Check all applicable options."
      options:
        - label: "Yes, always"
        - label: "Yes, sometimes"
        - label: "No"

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "Provide steps to reproduce the issue."
      placeholder: "1. ...\n2. ...\n3. ..."
    validations:
      required: true

  - type: number
    id: occurrences
    attributes:
      label: Number of Occurrences
      description: "Approximately how many times has this issue occurred?"
      placeholder: "Enter a number"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: Contact Email
      description: "If we need further information, what email can we reach you at?"
      placeholder: "Enter your email"
    validations:
      required: false

  - type: input
    id: url
    attributes:
      label: Related URL
      description: "If relevant, provide a link to where the issue can be observed."
      placeholder: "Enter URL"
    validations:
      required: false

  - type: date
    id: date-observed
    attributes:
      label: Date Observed
      description: "When did you first notice the bug?"
      placeholder: "YYYY-MM-DD"
    validations:
      required: false

  - type: file
    id: screenshot
    attributes:
      label: Screenshot or Log File
      description: "Attach a screenshot or log file if applicable."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for submitting your report. We'll get back to you as soon as we can."
