name: Testing Issue
description: Provide archive tool issue
title: "*Enter title here* - [Date: YYYY-MM-DD]"
labels: [tool-issue]
assignees: 
  - Andre-Diamond
projects: ["SingularityNET-Archive/3"]

body:
  - type: markdown
    attributes:
      value: "Thank you for taking the time to fill out this form."

  - type: checkboxes
    id: type
    attributes:
      label: Issue Type
      description: "Please select the type(s) of issue you are reporting."
      options:
        - label: "Bug/Defect"
        - label: "Feature Request"
        - label: "Template Issue"
        - label: "Performance Issue"
        - label: "Usability/Interface"
        - label: "Integration Issue"
        - label: "Documentation/Help"
        - label: "Security Concern"
        - label: "General Inquiry/Feedback"
    validations:
      required: true
 
  - type: textarea
    id: description
    attributes:
      label: Description
      description: "A detailed description of the issue."
      placeholder: "Describe the issue in detail..."
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: "Select the severity level of the issue."
      options:
        - "Please select"
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
      default: 0
    validations:
      required: true

  - type: input
    id: Workgroup
    attributes:
      label: Workgroup
      description: "Which workgroup does this affect?"
      placeholder: "All workgroups"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: "Any other context or information that could be helpful."
      placeholder: "Add any other context about the problem here."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "Thanks for submitting your report. We'll get back to you as soon as we can."
