# .github/workflows/commit-meeting-summaries.yml
name: Commit Meeting Summaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  commit-meeting-summaries:
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve Meeting Summaries
        id: retrieve-summaries
        run: |
          curl -X POST ${{ secrets.NETLIFY_BASE_URL }}/.netlify/functions/getMeetingSummaries \
            -H 'Content-Type: application/json' \
            -d '{}' \
            -o meeting-summaries.json
          summaries=$(cat meeting-summaries.json)
          summaries="${summaries//$'\n'/''}"
          summaries="${summaries//$'\r'/''}"
          echo "summaries=$summaries" >> $GITHUB_OUTPUT

      - name: Commit to GitHub
        run: |
          curl -X POST ${{ secrets.NETLIFY_BASE_URL }}/.netlify/functions/commitToGitHub \
            -H 'Content-Type: application/json' \
            -d '{
              "owner": "SingularityNET-Archive",
              "repo": "SingularityNET-Archive",
              "filePath": "Data/meeting-summaries.json",
              "content": ${{ toJson(steps.retrieve-summaries.outputs.summaries) }},
              "commitMessage": "Update meeting summaries"
            }'