# .github/workflows/commit-meeting-summaries.yml
name: Commit Meeting Summaries

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  commit-meeting-summaries:
    runs-on: ubuntu-latest

    steps:
      - name: Update GitHub Repository
        env:
          NETLIFY_BASE_URL: ${{ secrets.NETLIFY_BASE_URL }}
        run: |
          response=$(curl -s -X POST -H "Content-Type: application/json" "${NETLIFY_BASE_URL}/.netlify/functions/updateGitHubRepo")
          echo "Response from updateGitHubRepo: $response"

          # Check if the response indicates success
          if echo "$response" | grep -q '{"message": "Meeting summaries updated successfully"}'; then
            echo "Meeting summaries updated successfully"
          else
            echo "Error updating meeting summaries"
            exit 1
          fi